import * as mongoose from 'mongoose';
export const PostSchema = new mongoose.Schema({
  job_title: { type: String, required: true },
  job_links: { type: String },
  job_requirement: { type: String },
  logo: { type: String },
  company: { type: String },
  deadline: { type: String },
  working_type: { type: String },
  job_description: { type: String },
  job_benefit: { type: String },
  job_salary: { type: String },
  applied: { type: Array, default: [] },
  status: { type: Number, default: 0 },
  com_created: { type: String },
  com_location: { type: String },
  com_phone: { type: String },
  createdAt: { type: String },
  cv: { type: Object },
});
